import { createClientFromRequest } from 'npm:@base44/sdk@0.8.31';

const EXERCISES = [
  // Amputation exercises (leg amputees)
  {
    name: "Wall Seats",
    description: "Target the quadriceps and core muscles to enhance stability and endurance for standing longer periods with a prosthetic limb",
    instructions: "Position your back against a wall with your feet shoulder-width apart in front. Slide down the wall until your knees are at a 90-degree angle. Hold the position for 30 seconds and feel your leg muscles working.",
    category: "Strength",
    position: "Standing",
    difficulty: "Easy",
    muscles_used: ["Quadriceps", "Core"],
    equipment_needed: ["Wall"],
    restrictions: ["Severe knee pain", "Unable to weight-bear"],
    modifications: "Hold for shorter periods and progress gradually",
    default_sets: 2,
    default_reps: 1,
    default_duration_seconds: 30,
    safety_rating: "Safe",
    diagram_url: "https://cdn.prod.website-files.com/620223123d75ce5495043bfa/66f2c722b7da5e33d42d82fb_665ec7715cd4530f0bc79ff7_wall-seats-for-people-with-lower-limb-difference.jpeg",
    is_custom: false
  },
  {
    name: "Single-Leg Deadlift",
    description: "Strengthen the hamstrings, core, and gluteal muscles for stability during single-leg activities like walking with a prosthesis",
    instructions: "Stand with your feet hip-width apart. Hinge forward at your hips, keeping a straight back, and lift your prosthetic leg behind you. Return to the starting position, focusing on control and using your core muscles for stability. Repeat with the other leg.",
    category: "Strength",
    position: "Standing",
    difficulty: "Moderate",
    muscles_used: ["Hamstrings", "Glutes", "Core"],
    equipment_needed: [],
    restrictions: ["Balance disorders", "Recent amputation surgery"],
    modifications: "Use a wall or chair for balance",
    default_sets: 2,
    default_reps: 10,
    default_duration_seconds: null,
    safety_rating: "Safe",
    is_custom: false
  },
  {
    name: "Hip Bridges",
    description: "Strengthen the gluteal muscles, which are essential for core stability and power during walking, stair climbing, and other activities",
    instructions: "Lie on your back with knees bent and feet flat on the floor. Squeeze your buttocks and lift your hips off the floor until your body forms a straight line from shoulders to knees. Hold for a few seconds, then lower down slowly.",
    category: "Strength",
    position: "Lying down",
    difficulty: "Easy",
    muscles_used: ["Glutes", "Core"],
    equipment_needed: [],
    restrictions: ["Severe back pain", "Hip flexor tightness"],
    modifications: "Place a pillow under shoulders for support",
    default_sets: 2,
    default_reps: 10,
    default_duration_seconds: null,
    safety_rating: "Safe",
    diagram_url: "https://cdn.prod.website-files.com/620223123d75ce5495043bfa/66f2c723b7da5e33d42d831c_665ec88b321aeeba7e1c435c_hip-bridges-for-people-with-lower-limb-difference.jpeg",
    is_custom: false
  },
  {
    name: "Hamstring Stretch",
    description: "Improves flexibility in the back of the thigh, which is essential for a full range of motion during walking and other activities",
    instructions: "Sit on the floor with your sound side leg extended. Bend your prosthetic side leg, placing the sole of your foot against your inner thigh. Keeping your back straight, reach gently towards the toes of your extended leg until a stretch is felt in the back of your thigh. Hold for 30 seconds and repeat 3 times on each side.",
    category: "Flexibility",
    position: "Seated",
    difficulty: "Beginner",
    muscles_used: ["Hamstrings"],
    equipment_needed: [],
    restrictions: [],
    modifications: "Use a towel around the foot to assist",
    default_sets: 3,
    default_reps: 1,
    default_duration_seconds: 30,
    safety_rating: "Safe",
    is_custom: false
  },
  // Cardiac rehabilitation exercises
  {
    name: "Wall Press",
    description: "Builds upper body strength, improving stability and functional ability for daily activities",
    instructions: "Stand facing the wall, a few steps away. Place both hands just wider than shoulder width apart. Bend the elbows and lower your chest as close as possible to the wall. Push back up off the wall, straightening the elbows.",
    category: "Strength",
    position: "Standing",
    difficulty: "Easy",
    muscles_used: ["Chest", "Triceps", "Shoulders"],
    equipment_needed: ["Wall"],
    restrictions: ["Recent cardiac surgery", "Uncontrolled arrhythmia"],
    modifications: "Reduce depth of press if fatigued",
    default_sets: 2,
    default_reps: 10,
    default_duration_seconds: null,
    safety_rating: "Safe",
    is_custom: false
  },
  {
    name: "Seated Chest Press",
    description: "Strengthens chest and arm muscles in a controlled seated position, suitable for cardiac rehabilitation",
    instructions: "Sit on a chair and hold weights in your hands. Push forward, arms straight, keeping your elbows close to you. Bring hands back to the chest and repeat.",
    category: "Strength",
    position: "Seated",
    difficulty: "Easy",
    muscles_used: ["Chest", "Triceps"],
    equipment_needed: ["Weights", "Chair"],
    restrictions: ["Uncontrolled hypertension", "Recent chest surgery"],
    modifications: "Start with no weights, use water bottles",
    default_sets: 2,
    default_reps: 10,
    default_duration_seconds: null,
    safety_rating: "Safe",
    is_custom: false
  },
  {
    name: "Step Ups",
    description: "Builds lower body strength and endurance. Can be modified based on step height",
    instructions: "Stand tall and feet flat, shoulder width apart. Face the step and place your right foot on the step. Step upwards and straighten your leg at the top. Bring other leg up to stand on the step. Step down carefully behind the step. Perform on each leg.",
    category: "Strength",
    position: "Standing",
    difficulty: "Moderate",
    muscles_used: ["Quadriceps", "Glutes", "Hamstrings"],
    equipment_needed: ["Step"],
    restrictions: ["Severe knee pain", "Balance issues"],
    modifications: "Use a low step (2-3 inches), hold onto rail",
    default_sets: 2,
    default_reps: 10,
    default_duration_seconds: null,
    safety_rating: "Caution",
    is_custom: false
  },
  {
    name: "Side Steps",
    description: "Strengthens hip abductors and improves lateral stability",
    instructions: "Stand tall, arms by your side and keep feet together. If you need to, stand behind a chair with both hands on the back of the chair. Step out to the side with one leg. Bring your leg back towards your body at the centre. Repeat on each leg.",
    category: "Strength",
    position: "Standing",
    difficulty: "Easy",
    muscles_used: ["Hip Abductors", "Glutes"],
    equipment_needed: ["Chair"],
    restrictions: ["Hip surgery", "Balance disorders"],
    modifications: "Hold onto chair for support, smaller steps",
    default_sets: 2,
    default_reps: 10,
    default_duration_seconds: null,
    safety_rating: "Safe",
    is_custom: false
  },
  {
    name: "Seated Triceps Dips",
    description: "Strengthens the triceps and back of arms without excessive upper body stress",
    instructions: "Sit on a firm chair with your arms at your sides slightly bent. Lift your buttocks off the chair by pushing down with your hands to straighten the elbows. Gently lower back down into the chair.",
    category: "Strength",
    position: "Seated",
    difficulty: "Easy",
    muscles_used: ["Triceps"],
    equipment_needed: ["Chair"],
    restrictions: ["Shoulder impingement", "Recent shoulder surgery"],
    modifications: "Perform on chair with low, sturdy armrests",
    default_sets: 2,
    default_reps: 10,
    default_duration_seconds: null,
    safety_rating: "Safe",
    is_custom: false
  },
  {
    name: "Half Squat",
    description: "Builds leg strength with reduced range of motion, suitable for cardiac patients and those with limitations",
    instructions: "Stand in front of a chair/counter and hold onto it. Keep back straight, slowly lower yourself towards the chair (not sitting down fully), then push through your legs and feet and push upwards.",
    category: "Strength",
    position: "Standing",
    difficulty: "Moderate",
    muscles_used: ["Quadriceps", "Glutes"],
    equipment_needed: ["Chair"],
    restrictions: ["Severe knee pain", "Severe hip arthritis"],
    modifications: "Use full range initially, reduce gradually",
    default_sets: 2,
    default_reps: 10,
    default_duration_seconds: null,
    safety_rating: "Caution",
    is_custom: false
  },
  // Asthma exercises
  {
    name: "Brisk Walking",
    description: "Low-impact aerobic exercise suitable for people with asthma when performed in appropriate conditions",
    instructions: "Walk at a moderate pace where you can hold a conversation. Warm up for 10 minutes before starting. Cool down for 10 minutes after. Ensure you have your inhaler nearby.",
    category: "Cardio",
    position: "Standing",
    difficulty: "Easy",
    muscles_used: ["Heart", "Legs"],
    equipment_needed: ["Comfortable shoes"],
    restrictions: ["Uncontrolled asthma", "Cold air sensitivity", "High pollution days"],
    modifications: "Exercise indoors, mid-to-late morning timing",
    default_sets: 1,
    default_reps: null,
    default_duration_seconds: 1800,
    safety_rating: "Safe",
    is_custom: false
  },
  {
    name: "Cycling",
    description: "Low-impact aerobic activity good for building endurance with asthma",
    instructions: "Start with a warm-up on an exercise bike or outdoor cycle. Maintain a pace where you can still talk. Continue for 20-30 minutes. Cool down with 10 minutes of easy pedaling.",
    category: "Cardio",
    position: "Seated",
    difficulty: "Easy",
    muscles_used: ["Legs", "Heart"],
    equipment_needed: ["Bicycle or exercise bike"],
    restrictions: ["Uncontrolled exercise-induced asthma"],
    modifications: "Use stationary bike to control environment",
    default_sets: 1,
    default_reps: null,
    default_duration_seconds: 1800,
    safety_rating: "Safe",
    is_custom: false
  },
  {
    name: "Swimming",
    description: "Excellent low-impact aerobic exercise for people with asthma due to warm, humid air around pool",
    instructions: "Start with 10-minute warm-up of easy swimming. Gradually increase duration. The warm, humid air helps prevent asthma symptoms. Have your rescue inhaler poolside.",
    category: "Cardio",
    position: "Any",
    difficulty: "Easy",
    muscles_used: ["Full body"],
    equipment_needed: ["Pool"],
    restrictions: [],
    modifications: "Start in shallow water if learning",
    default_sets: 1,
    default_reps: null,
    default_duration_seconds: 1800,
    safety_rating: "Safe",
    is_custom: false
  },
  // Spinal Cord Injury (Paraplegia) exercises
  {
    name: "Back Row (Wheelchair)",
    description: "Strengthens the back muscles for improved posture and functional strength with spinal cord injury",
    instructions: "Using an exercise band anchored at shoulder height, pull the band towards your body, bringing your elbows back. Hold for a moment, then slowly return to starting position. Focus on controlled movement.",
    category: "Strength",
    position: "Seated",
    difficulty: "Moderate",
    muscles_used: ["Back", "Biceps"],
    equipment_needed: ["Resistance band"],
    restrictions: ["Shoulder instability", "Recent spinal surgery"],
    modifications: "Adjust resistance band position, use lighter band",
    default_sets: 3,
    default_reps: 8,
    default_duration_seconds: null,
    safety_rating: "Safe",
    is_custom: false
  },
  {
    name: "Bicep Curl (Wheelchair)",
    description: "Builds arm strength essential for wheelchair mobility and transfers",
    instructions: "Anchor a resistance band under your foot or hold weights. Keeping your elbows at your sides, curl your hands up towards your shoulders. Lower slowly. Perform on both sides.",
    category: "Strength",
    position: "Seated",
    difficulty: "Easy",
    muscles_used: ["Biceps"],
    equipment_needed: ["Weights or resistance band"],
    restrictions: [],
    modifications: "Start with lighter weights",
    default_sets: 3,
    default_reps: 8,
    default_duration_seconds: null,
    safety_rating: "Safe",
    is_custom: false
  },
  {
    name: "Lat Pulldown (Wheelchair)",
    description: "Strengthens back and shoulder muscles for stability and functional mobility",
    instructions: "Sit upright in your wheelchair. Grip the resistance band or cable above your head. Pull downward in a controlled motion, bringing your hands toward your shoulders. Return to starting position.",
    category: "Strength",
    position: "Seated",
    difficulty: "Moderate",
    muscles_used: ["Latissimus dorsi", "Back"],
    equipment_needed: ["Resistance band"],
    restrictions: ["Shoulder impingement"],
    modifications: "Reduce range of motion if needed",
    default_sets: 3,
    default_reps: 8,
    default_duration_seconds: null,
    safety_rating: "Safe",
    is_custom: false
  },
  // Below-knee amputation exercises
  {
    name: "Hip Abduction Stretch",
    description: "Maintains hip flexibility and prevents contractures common after lower limb amputation",
    instructions: "Sit with your back against a wall or head of bed. Put your amputated limb out to the side and bend the other leg slightly. Push on the thigh, so you feel a stretch in your inner thigh. Make sure both buttocks remain on the floor.",
    category: "Flexibility",
    position: "Seated",
    difficulty: "Beginner",
    muscles_used: ["Hip adductors"],
    equipment_needed: [],
    restrictions: [],
    modifications: "Reduce range of motion initially",
    default_sets: 1,
    default_reps: 1,
    default_duration_seconds: 20,
    safety_rating: "Safe",
    is_custom: false
  },
  {
    name: "Quad Sets",
    description: "Strengthens the thigh muscles essential for prosthetic walking and control",
    instructions: "Push the back of your knee down against the bed to tighten your thigh muscle. Hold for 5 seconds and release. Do this exercise on your amputated and non-amputated leg.",
    category: "Strength",
    position: "Lying down",
    difficulty: "Beginner",
    muscles_used: ["Quadriceps"],
    equipment_needed: [],
    restrictions: [],
    modifications: "Hold for shorter periods initially",
    default_sets: 1,
    default_reps: 10,
    default_duration_seconds: null,
    safety_rating: "Safe",
    is_custom: false
  },
  {
    name: "Hip Extension",
    description: "Strengthens the gluteal muscles critical for walking balance and prosthetic control",
    instructions: "Lie on your stomach. Lift your amputated limb towards the ceiling keeping your knee straight. Hold and then return to the starting position.",
    category: "Strength",
    position: "Lying down",
    difficulty: "Easy",
    muscles_used: ["Glutes"],
    equipment_needed: [],
    restrictions: ["Recent hip surgery"],
    modifications: "Hold for shorter duration initially",
    default_sets: 1,
    default_reps: 10,
    default_duration_seconds: null,
    safety_rating: "Safe",
    is_custom: false
  },
  // General strength and mobility
  {
    name: "Shoulder Press (Seated)",
    description: "Builds shoulder and arm strength while seated, suitable for many ability levels",
    instructions: "Sit on the edge of a chair, keeping your back straight. Bring your arms up so you have an L shape at the elbow joint and keep your wrists in line with your forearms. Look straight ahead and push your hands upwards so the arms straighten. Slowly return.",
    category: "Strength",
    position: "Seated",
    difficulty: "Easy",
    muscles_used: ["Shoulders", "Triceps"],
    equipment_needed: ["Weights"],
    restrictions: ["Shoulder impingement", "Rotator cuff injury"],
    modifications: "Use lighter weights, reduce range",
    default_sets: 2,
    default_reps: 10,
    default_duration_seconds: null,
    safety_rating: "Safe",
    is_custom: false
  },
  {
    name: "Standing Knee Raises",
    description: "Improves hip flexor strength and mobility",
    instructions: "Stand tall, looking forward and keep tummy tight. Let your arms hang freely by your side. Raise your knee up to hip height, tap your opposite hand to your knee and hold for a second or two. Gently lower and repeat on other leg.",
    category: "Strength",
    position: "Standing",
    difficulty: "Easy",
    muscles_used: ["Hip flexors", "Core"],
    equipment_needed: ["Chair for balance"],
    restrictions: ["Severe hip arthritis"],
    modifications: "Use chair or wall for balance",
    default_sets: 2,
    default_reps: 10,
    default_duration_seconds: null,
    safety_rating: "Safe",
    is_custom: false
  },
  {
    name: "Shoulder Shrugs",
    description: "Improves shoulder and neck mobility and warmup exercise",
    instructions: "Stand or sit upright. Raise your shoulders up towards your ears, hold for a moment, then relax and lower. Repeat in a controlled manner.",
    category: "Warmup",
    position: "Any",
    difficulty: "Beginner",
    muscles_used: ["Shoulder", "Neck"],
    equipment_needed: [],
    restrictions: [],
    modifications: "Can be done seated or standing",
    default_sets: 1,
    default_reps: 10,
    default_duration_seconds: null,
    safety_rating: "Safe",
    is_custom: false
  }
];

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });

    // Bulk create all exercises
    const created = await base44.entities.Exercise.bulkCreate(EXERCISES);
    
    return Response.json({ 
      success: true, 
      message: `Imported ${EXERCISES.length} exercises covering all abilities`,
      count: created.length 
    });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});