import React from "react";
import { Link } from "react-router-dom";
import { ChevronLeft } from "lucide-react";

export default function TermsConditions() {
  return (
    <div className="max-w-3xl mx-auto py-8 px-4 pb-20 md:pb-8">
      <Link to="/settings" className="flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground mb-6">
        <ChevronLeft className="w-4 h-4" /> Back to Settings
      </Link>
      <h1 className="text-3xl font-heading font-bold mb-2">Terms & Conditions</h1>
      <p className="text-sm text-muted-foreground mb-8"><strong>Effective Date:</strong> June 23, 2025 &nbsp;|&nbsp; <strong>Last Updated:</strong> June 23, 2025</p>

      <div className="space-y-6 text-sm text-muted-foreground leading-relaxed">

        <section>
          <h2 className="text-base font-semibold text-foreground mb-2">1. Acceptance of Terms</h2>
          <p>By accessing or using FitAbility ("the App", "we", "our"), you agree to be bound by these Terms & Conditions and our <Link to="/privacy" className="text-primary underline">Privacy Policy</Link>. If you do not agree, you must not use the App. These terms constitute a legally binding agreement between you and FitAbility.</p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-foreground mb-2">2. Description of Service</h2>
          <p>FitAbility provides AI-generated, adaptive fitness and exercise recommendations tailored to individuals with disabilities, chronic conditions, injuries, limited mobility, and rehabilitation needs. The service is provided on an "as is" and "as available" basis.</p>
          <p className="mt-2 font-medium text-foreground">FitAbility is NOT a medical service. It is NOT a substitute for professional medical advice, diagnosis, treatment, or physical therapy. Always consult a qualified healthcare provider before beginning any exercise programme.</p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-foreground mb-2">3. Eligibility</h2>
          <p>You must be at least 13 years of age (or 16 in the European Union) to use this App. By using FitAbility, you represent that you meet this requirement.</p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-foreground mb-2">4. User Responsibilities</h2>
          <p>You agree to:</p>
          <ul className="list-disc pl-6 mt-2 space-y-1">
            <li>Provide accurate, current, and complete health and profile information.</li>
            <li>Keep your account credentials secure and not share them.</li>
            <li>Consult your physician or physical therapist before starting any exercise programme.</li>
            <li>Stop exercising immediately if you experience pain, chest tightness, dizziness, shortness of breath, or any other unusual symptom — and seek medical attention if appropriate.</li>
            <li>Not use the App as a replacement for emergency medical care. Call emergency services (e.g. 911) if you are in immediate danger.</li>
            <li>Not misuse the App, attempt to reverse-engineer it, or engage in any unlawful conduct.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-base font-semibold text-foreground mb-2">5. Medical Disclaimer</h2>
          <p>Exercise carries inherent risks. The exercise recommendations generated by FitAbility are based solely on the information you provide. We cannot verify medical diagnoses and make no warranty that recommendations are safe or suitable for your specific condition. You exercise entirely at your own risk.</p>
          <p className="mt-2">See the full <Link to="/medical-disclaimer" className="text-primary underline">Medical Disclaimer</Link> for additional details.</p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-foreground mb-2">6. Intellectual Property</h2>
          <p>All content, code, designs, trademarks, logos, graphics, and AI-generated output within FitAbility are owned by or licensed to FitAbility. You may not reproduce, distribute, modify, create derivative works from, publicly display, or commercially exploit any part of the App without prior written permission.</p>
          <p className="mt-2">You retain ownership of data you submit (e.g. your health profile), but grant us a limited licence to process it for the purpose of providing the service.</p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-foreground mb-2">7. Limitation of Liability</h2>
          <p>To the fullest extent permitted by applicable law, FitAbility and its creators, employees, and affiliates shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising from:</p>
          <ul className="list-disc pl-6 mt-2 space-y-1">
            <li>Personal injury or aggravation of existing conditions resulting from following exercise recommendations.</li>
            <li>Reliance on AI-generated content without independent medical verification.</li>
            <li>Loss of data, loss of service, or interruption of the App.</li>
            <li>Any other use or inability to use the App.</li>
          </ul>
          <p className="mt-2">In jurisdictions that do not allow exclusion of certain warranties or limitation of liability, our liability is limited to the maximum extent permitted by law.</p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-foreground mb-2">8. Indemnification</h2>
          <p>You agree to indemnify and hold harmless FitAbility and its creators from any claims, losses, damages, liabilities, and expenses (including reasonable legal fees) arising from your use of the App, violation of these Terms, or violation of any applicable law.</p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-foreground mb-2">9. Termination</h2>
          <p>We reserve the right to suspend or terminate your account at any time for violation of these Terms or for any other reason at our discretion. You may delete your account at any time via the <Link to="/delete-account" className="text-primary underline">Delete My Account</Link> page.</p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-foreground mb-2">10. Governing Law</h2>
          <p>These Terms are governed by and construed in accordance with the laws of the State of Texas, United States, without regard to conflict of law principles. Any disputes shall be resolved in the competent courts of Texas.</p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-foreground mb-2">11. Changes to These Terms</h2>
          <p>We may update these Terms at any time. Continued use of the App after changes constitutes your acceptance of the revised Terms. We will notify you of material changes via the App or email.</p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-foreground mb-2">12. Contact</h2>
          <p>For questions about these Terms, contact us at <a href="mailto:mediocreatbestdev@outlook.com" className="text-primary underline">mediocreatbestdev@outlook.com</a>.</p>
        </section>

      </div>
    </div>
  );
}