import React from "react";
import { Link } from "react-router-dom";
import { ChevronLeft } from "lucide-react";

export default function TermsConditions() {
  return (
    <div className="max-w-3xl mx-auto py-8 px-4 pb-20 md:pb-8">
      <Link to="/settings" className="flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground mb-6">
        <ChevronLeft className="w-4 h-4" /> Back to Settings
      </Link>
      <h1 className="text-3xl font-heading font-bold mb-6">Terms & Conditions</h1>
      <div className="prose prose-sm max-w-none text-muted-foreground space-y-4">
        <p><strong>Last updated:</strong> {new Date().toLocaleDateString()}</p>
        <h2 className="text-lg font-semibold text-foreground">Acceptance of Terms</h2>
        <p>By using FitAbility, you agree to these terms and conditions. If you do not agree, please do not use the application.</p>
        <h2 className="text-lg font-semibold text-foreground">Service Description</h2>
        <p>FitAbility provides AI-generated exercise recommendations for individuals with disabilities, chronic pain, injuries, and mobility limitations. The service is not a substitute for professional medical advice, physical therapy, or physician guidance.</p>
        <h2 className="text-lg font-semibold text-foreground">User Responsibilities</h2>
        <ul className="list-disc pl-6 space-y-1">
          <li>Provide accurate health and disability information</li>
          <li>Consult your healthcare provider before starting any exercise program</li>
          <li>Stop exercising immediately if you experience pain, dizziness, or discomfort</li>
          <li>Do not use this app as a replacement for medical care</li>
        </ul>
        <h2 className="text-lg font-semibold text-foreground">Limitation of Liability</h2>
        <p>FitAbility and its creators are not liable for any injury, health complications, or damages resulting from following exercise recommendations generated by the application.</p>
      </div>
    </div>
  );
}